### ISSUE TITLE
Different logic used to analyse DSL for stubs and tests

### ISSUE THREAD

**Issue by OlgaMaciaszek** [Codearte/accurest#105]
The groovy DSL files are being analysed independently while creating stubs and tests which results in incoherent outputs. For example, such a script:

``` groovy
io.codearte.accurest.dsl.GroovyDsl.make {
 request {
  method('POST')
  url("test")
  headers {
   header("Content-Type": "application/json")
  }
  body("")
 }

 response {
  status 406
 }
}
```

will have the content type evaluated as JSON for the stub and as UNKNOWN for the test.

There should be a coherent way of processing DSLs both for tests and for stubs.

**Comment by marcingrzejszczak** [comment]
That's been more or less fixed with the JSON path approach :)
