### ISSUE TITLE
ResponseBody can't be validated against single value returned from endpoint

### ISSUE THREAD

**Issue by cameleeck** [Codearte/accurest#108]
Sometimes API are returning single values for example
`int countMethod();` 
Currently Accurest can validate only against lists or maps it's impossible to tests such endpoints in proper way.

I'm proposing to make possible write something like:
`
    response {
        body('5')
        status 200
    }
`

**Comment by OlgaMaciaszek** [comment]
fix/#108-single-value-validation-fix-after-#106-merge
