### ISSUE TITLE
Configuration to run generated tests from IntelliJ

### ISSUE THREAD

**Issue by adamwojszczyk** [Codearte/accurest#116]
Sometimes I want to run single test to found out what is a problem. To do it I copy it to test directory and run it. I would like to be able to run accurest tests from directory where they are generated.

**Comment by jkubrynski** [comment]
@adam-wojszczyk there is a problem with intellij - https://youtrack.jetbrains.com/issue/IDEA-135096
It'll work after they fix this issue.
For now the walkaround is to generate tests into test directory
