### ISSUE TITLE
Better naming for server()/client() definition

### ISSUE THREAD

**Issue by mariuszs** [Codearte/accurest#127]
I propose something like

```
${stub(...), spec(...)}
```

This is always readable and not confusing. stub is for client usage, specification tests server implementation.

**Comment by adamwojszczyk** [comment]
+1

**Comment by marcingrzejszczak** [comment]
Go ahead with a PR :) You can create an alias for `client` and `server` by providing `stub` and `spec` - it will be an extremely easy change

**Comment by adamwojszczyk** [comment]
I suggest to use "test" instead of "spec".

**Comment by marcingrzejszczak** [comment]
+1 for `Stub` and `Test`

**Comment by marcingrzejszczak** [comment]
@adam-wojszczyk - where's the PR? ;)

**Comment by adamwojszczyk** [comment]
You have merged it... ;)
https://github.com/Codearte/accurest/commit/fc69c961efe1493bcceb783932eecc5479c60d92

**Comment by marcingrzejszczak** [comment]
LOL :D
