### ISSUE TITLE
Consider changing Wiremock to sth else

### ISSUE THREAD

**Issue by marcingrzejszczak** [Codearte/accurest#132]
Due to lack of responsiveness of the Wiremock's author to changes (obsolete libs etc.) - https://github.com/tomakehurst/wiremock/issues/261 we should consider doing sth about it

**Comment by tomakehurst** [comment]
Just to point this out: I left 1 obsolete lib in 1.x because to do otherwise would have been a breaking change, and I've now updated in in 2.0.0-beta.

How does that constitute a lack of responsiveness?

**Comment by jkubrynski** [comment]
@tomakehurst wiremock is powerful project and we're very glad there is beta version released. The case is we're waiting for this since Apr 20 :)

**Comment by mariuszs** [comment]
@tomakehurst Im not sure if this is breaking change, but this is breaking bug for sure :) 

https://github.com/tomakehurst/wiremock/issues/261

**Comment by tomakehurst** [comment]
I'm not disputing that, but jsonpath 2 also changes the syntax in ways that broke several of wiremock's tests.

**Comment by mariuszs** [comment]
we are happy now with wiremock 2 :v:
