### ISSUE TITLE
Incorrect assert generation for Maps

### ISSUE THREAD

**Issue by tdziurko** [Codearte/accurest#149]
I have a LoanBean class with property

```
Map<Integer, BigDecimal> extensions = [:]
```

with key-value pairs (7, 0), (14, 0), (30, 0)

and this class is serialized into JSON. Stubs generated by Accurest contain not compiling asserts:

```
responseBody.extensions.14 == 0
responseBody.extensions.30 == 0
responseBody.extensions.7 == 0
```

I believe it should be something like

```
responseBody.extensions.'14' == 0
```

**Comment by marcingrzejszczak** [comment]
Did you upgrade accurest to the neeset version?

IF the response is JSON you should have json paths

**Comment by mariuszs** [comment]
Error report without specified version is useless ;)

**Comment by marcingrzejszczak** [comment]
@tdziurko - please check the latest version. It should work there. PIng us back so we can close the ticket.

**Comment by tdziurko** [comment]
Yeah, latest version is fine. Sorry for unnecessary noise.
