### ISSUE TITLE
JsonPath matchers generated for service stubs are incorrect

### ISSUE THREAD

**Issue by wojciechgizynski** [Codearte/accurest#162]
I have made a Groovy Dsl with the body part which goes like this:

``` groovy
body(
    name: 'Jan',    
    surname: 'Kowalski',
    age: 29
)
```

The request body I'm expecting is like this:

``` json
{
    "name": "Jan",
    "surname": "Kowalski",
    "age": 29
 }
```

These are the matchers I get for request body when I generate stubs with Accurest:

``` json
"bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.name == 'Jan')]"
    }, {
      "matchesJsonPath" : "$[?(@.surname == 'Kowalski')]"
    }, {
      "matchesJsonPath" : "$[?(@.age == 29)]"
    } ]
```

The problem is that the wiremock is complaining that the request didn't match against the defined stub. It does work once you modify the request to have all important fields as members of a list:

``` json
[
    {"name": "Jan"},
    {"surname": "Kowalski"},
    {"age": 29}
]
```

I've read http://goessner.net/articles/JsonPath/ and some other articles about JsonPath. It seems to me that the value cannot be verified for the JSON field from the JsonPath query unless the appropriate field is a list. Filtering ?(<expression>) only works on list elements of the JSON document.

I also think it's a good idea to add a test which would verify that JsonPath matchers generated from Groovy Dsl definition are actually matching the desired request body.

**Comment by marcingrzejszczak** [comment]
For the root parameters we could do such a check: http://wiremock.org/stubbing.html#json-body-matching

So we would have:

```
"bodyPatterns" : [ {
      { "equalToJson" : "{ \"name\": \"Jan\" ........ }", "jsonCompareMode": "LENIENT" }
    }, {
      "matchesJsonPath" : "for anything list related not in root"
    } ]
```

WDYT? Could you please check if that works?

**Comment by marcingrzejszczak** [comment]
Actually this will not work for regex... :/

**Comment by marcingrzejszczak** [comment]
I've managed to set a JSONPath to find that Kowalski guy.

Go here:

http://jsonpath.herokuapp.com/?path=$..book[?(@.price%20%3C=%20$[%27expensive%27])]

Type in the JSON:

```
{
    "name": "Jan",
    "surname": "Kowalski",
    "age": 29
 }
```

This is the path

```
$[?($.name === @ && @ == 'Kowalski')]
```

Pick the Goessner implementation of JSONPath. I took it from here: http://stackoverflow.com/questions/25031187/jsonpath-selecting-root-level-field-if-satisfies-a-condition 

Like the author of the answer says - it might be error prone. Unfortunately we have nothing better ;)

Could you please take a look if it works with Wiremock? Also please check if in the created test the assertion will work from Jayway JSONPath's perspective.

Also feel free to modify the Wiremock tests with the extension that you've suggested :)

> I also think it's a good idea to add a test which would verify that JsonPath matchers generated from Groovy Dsl definition are actually matching the desired request body.

**Comment by mariuszs** [comment]
I think this issue was resolved with json-path 2.0 and latest accurest. Please verify json-path version. Related issue from wiremock: https://github.com/tomakehurst/wiremock/issues/261

**Comment by yu55** [comment]
@mariuszs 
I'm using:
- accurest 0.9.7
- micro-infra 0.9.6
- json-path 2.0.0

and still WireMock returns 404 when request has JSON body.

**Comment by mariuszs** [comment]
@yu55 Please show us your contract, spec and stub data. 

Btw: Is this related to this issue?

**Comment by yu55** [comment]
@mariuszs Below are things you asked.

Contract:

```
io.codearte.accurest.dsl.GroovyDsl.make {
    request {
        method 'POST'
        url $(client('/ws/some/path'), server('/some/path'))
        headers {
            header 'Content-Type': 'application/json'
        }
        body(
                field1: $(
                        client(regex('.*')),
                        server('field1Value')),
                field2: $(
                        client(regex('.*')),
                        server('field2Value')),
                field3: $(
                        client(regex('.*')),
                        server('field3Value')),
        )
    }
    response {
        status 200
    }
}
```

Generated stub:

```
{
  "request" : {
    "url" : "/ws/some/path",
    "method" : "POST",
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.field1 =~ /.*/)]"
    }, {
      "matchesJsonPath" : "$[?(@.field2 =~ /.*/)]"
    }, {
      "matchesJsonPath" : "$[?(@.field3 =~ /.*/)]"
    } ],
    "headers" : {
      "Content-Type" : {
        "equalTo" : "application/json"
      }
    }
  },
  "response" : {
    "status" : 200
  }
}
```

Request execution:

```
        serviceRestClient.forService(new ServiceAlias("myService"))
                .post()
                .onUrl("ws/some/path")
                .body(myRequestBody)
                .withHeaders().contentType(MediaType.APPLICATION_JSON)
                .andExecuteFor()
                .ignoringResponse();
```

where:

```
class MyRequestBody {

    private String field1;

    private String field2;

    private String field3;

    public CreateLedgerRequestBody(String field1, String field2, String field3) {
        this.field1 = field1;
        this.field2 = field2;
        this.field3 = field3;
    }

    public String getField1() {
        return field1;
    }

    public String getField2() {
        return field2;
    }

    public String getField3() {
        return field3;
    }
}
```

When I send above request i get 404 from WireMock.
When I change contract so that it doesn't have body and execute request without body WireMock responds with 200 OK. So for me WireMock cannot handle JSON as body in request (and I think that it's probably JSON body matching issue).

**Comment by mariuszs** [comment]
@marcingrzejszczak 

```
$[?($.name === @ && @ == 'Kowalski')]
```

I am sure that the name is 'Jan' and this works  :bomb: 

```
$.[?(@.name == 'Jan')]
```

this works too:

```
$.[?(@.name =~ /Ja.*/)]
```

**Comment by mariuszs** [comment]
Sample test with wiremock-2.0.2-standalone

``` json
{
  "request": {
    "url": "/foo",
    "method": "POST",
    "bodyPatterns": [
      {
        "matchesJsonPath": "$[?(@.name =~ /Jan.*/)]"
      }
    ]
  },
  "response": {
    "status": 200
  }
}
```

```
2015-10-14 23:12:36.676 Received request: (POST //localhost:8080/foo)@1870446185 org.eclipse.jetty.server.Request@6f7cbe69
2015-10-14 23:12:36.677 Request received:
(POST //localhost:8080/foo)@1870446185 org.eclipse.jetty.server.Request@6f7cbe69{
"name":"Janek"
```

Request with curl

```
curl  -H "Content-Type: application/json"  -vvX POST http://localhost:8080/foo -d @body.json
```

with body.json

``` json
{
"name":"Janek"
}
```

Result with 200

**Comment by marcingrzejszczak** [comment]
@yu55 and @wojciechgizynski - are you sure you are using latest Wiremock?

**Comment by mariuszs** [comment]
@yu55 Your stub works for me too:

```
 curl -H "Content-Type: application/json" -vvX POST http://localhost:8080/ws/some/path -d @a.json
```

``` json
{
"field1":"foo",
"field2": "abd",
"field3": "cdd"
}
```

**Comment by yu55** [comment]
My wiremock version is 2.0.4-beta.
It started to work properly... although I'm not sure what the real problem was.

**Comment by marcingrzejszczak** [comment]
can we close it?

**Comment by wojciechgizynski** [comment]
I would like to first recheck the problem on my end. I was testing with the
WireMock 2.0.0 standalone and the problem persisted.
15.10.2015 9:24 PM "Marcin Grzejszczak" notifications@github.com
napisał(a):

**Comment by marcingrzejszczak** [comment]
can we close it?

**Comment by yu55** [comment]
@marcingrzejszczak From my point of view this issue can be closed.
Not sure about @wojciechgizynski though.

**Comment by wojciechgizynski** [comment]
Sorry for leaving this open for so long. I will get to it later today.
The problem I encountered is still there - generated stubs don't work properly with most up-to-date standalone version of WireMock (http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/), which is beta 2.0.0. 

If the issue isn't present with the higher version of WireMock, then it would be good idea to ask for updated release of WM standalone and to add some kind of note about this to the AccuREST wiki.

**Comment by marcingrzejszczak** [comment]
@wojciechgizynski you've closed it cause everything is fine or what? :P

**Comment by wojciechgizynski** [comment]
Yes, I've closed it because there's no point of keeping it open - nothing to do here :)
