### ISSUE TITLE
Lower case http methods in generated stubs

### ISSUE THREAD

**Issue by LukasSmrcka** [Codearte/accurest#171]
When accurest generates stubs......
eg.
def response = webTarget
.path('/v1/payment_requests/e86df6f693de4b35ae648464c5b0dc08')
.request()
.method('get')

The 'get' is lower case.

It should be upper case. Than it will be compatible with servers that use jersey rest

USE CASE:
When I create base class for generated tests that runs whole spring context where jersey REST is used (org.glassfish.jersey).
Than I get 404 from server when http methods are lower case. 
With upper case everything is ok

**Comment by marcingrzejszczak** [comment]
@LukasSmrcka  - Can you present the whole obfuscated Groovy DSL?

**Comment by LukasSmrcka** [comment]
Hi Marcin,
sure I can. Anyway, have you discussed this with Jakub? I think he allready started to work on this.

io.codearte.accurest.dsl.GroovyDsl.make {
    request {
        method "GET"
        url "/v1/some_cool_requests/e86df6f693de4b35ae648464c5b0dc08"
    }
    response {
        status 200
        headers {
            header('Content-Type': 'application/json;charset=UTF-8')
        }
        body """
                {"id":"789fgh","other_data":1268}
             """
    }
}

**Comment by LukasSmrcka** [comment]
I´ve also sent to Jakub base class for generated specs

**Comment by marcingrzejszczak** [comment]
For such a contract:

```
io.codearte.accurest.dsl.GroovyDsl.make {
request {
method "get"
url "/v1/some_cool_requests/e86df6f693de4b35ae648464c5b0dc08"
}
response {
status 200
headers {
header('Content-Type': 'application/json;charset=UTF-8')
}
body """
{"id":"789fgh","other_data":1268}
"""
}
}
```

it will produce:

```
 when:
  def response = webTarget
    .path('/v1/some_cool_requests/e86df6f693de4b35ae648464c5b0dc08')
    .request()
    .method('GET')

  String responseAsString = response.readEntity(String)

 then:
  response.status == 200
  response.getHeaderString('Content-Type') == 'application/json;charset=UTF-8'
 and:
  DocumentContext parsedJson = JsonPath.parse(responseAsString)
  !parsedJson.read('''$[?(@.other_data == 1268)]''', JSONArray).empty
  !parsedJson.read('''$[?(@.id == '789fgh')]''', JSONArray).empty
```

is it ok?

**Comment by LukasSmrcka** [comment]
It is Good.... Thanks Marcin .)
