### ISSUE TITLE
Provide light mechanism to evaluate DSL and check result

### ISSUE THREAD

**Issue by jkubrynski** [Codearte/accurest#179]
Currently we do it with Nebula, but something more scalable and build-tool independent is welcome

**Comment by szpak** [comment]
[EmbeddedSpecification](https://github.com/spockframework/spock/blob/master/spock-specs/src/test/groovy/org/spockframework/EmbeddedSpecification.groovy) from Spock could be some reference point.

**Comment by marcingrzejszczak** [comment]
Gradle TestKit is done
