### ISSUE TITLE
Provide support for Wiremock scenarios

### ISSUE THREAD

**Issue by pawelus** [Codearte/accurest#182]
Support for Wiremock stateful behaviour as described in [Wiremock documentation](http://wiremock.org/stateful-behaviour.html) as it would allow UI testers to run complex test scenarios.

**Comment by jkubrynski** [comment]
@pawelus you can test scenarios with accurest 1.0.0-RC1. It's documented here: https://github.com/Codearte/accurest/wiki/7.-Scenarios

**Comment by pawelus** [comment]
@jkubrynski - tested client stub generation with scenarios and it looks great!

Big big thanks!

**Comment by jkubrynski** [comment]
Cool! :)
