### ISSUE TITLE
Single quotes not escaped when generating Spock tests

### ISSUE THREAD

**Issue by pawelus** [Codearte/accurest#193]
For dsl with response body:

> '''
> {
>     "text" : "text with 'quotes' inside"
> }
> '''

the output of gnerateAccurest is:

> !parsedJson.read('''$[?(@.text == 'text with 'quotes' inside')]''', JSONArray).empty

quotes inside text are not escaped and cause unexpected char: ''' errors

**Comment by marcingrzejszczak** [comment]
Fixed in JSONAssert
