### ISSUE TITLE
Add multiple base test classes support

### ISSUE THREAD

**Issue by OlgaMaciaszek** [Codearte/accurest#205]
A base test classes could be optionally defined in the DSL script and override the one provided in the plugin configuration.

**Comment by dilipkrish** [comment]
@OlgaMaciaszek Is the intent of this issue to support overriding the controller to be mocked in the server side stub?

For e.g. If a service has [more than one controller](https://github.com/Codearte/accurest-samples/blob/master/http-server/src/test/groovy/com/toomuchcoding/MvcSpec.groovy#L8-L10) how does one specify the base class.

**Comment by marcingrzejszczak** [comment]
Until now all the controllers would be set up in one base class. That could lead to a mess so what I suggested was to decouple different controller settings into for example Spring beans. Then you could set up different controller configurations (with all the deps stubbed out) in different parts of your codebase and then have them injected into a single base class

**Comment by dilipkrish** [comment]
It might seem a little expensive to load up the spring context for every test suite no? Also Im wondering about the test isolation when for e.g. we're testing the `FraudController` but other controllers are contributing to the context. 

Could you elaborate your solution? May be I could take a stab at a PR to address this

**Comment by marcingrzejszczak** [comment]
The spring context wouldn't be the one from you application. You could set up a test context specific for the tests (that spring context would boot up in no time).

We used to assume that every controller would have a service that it would delegate its calls to i.e. `FraudController` would delegate all the calls to `FraudService`. Now, in your tests you could set up a context in which you would register `FraudController` as a bean that would have `FraudService` injected as a mock.

Pseudocode:

```

@RestController FraudController {
    private final FraudService fraudService;

    @Autowired
    // constructor injection

    // RequestMapping methods
    String someMethod() {
        return fraudService.doSth();
    }
}

@Configuration
class FraudTestsConfig {

    @Bean
    FraudService fraudService() {
        FraudService fraudService = Mockito.mock(FraudService.class); // or just an impl of an interface
        // mock what you need
        return fraudService;
    }
}

@ContextConfiguration(classes = [FraudTestsConfig,...], loader=...) // or junit setup - doesn't matter 
class AccurestBaseClass extends Specification  { 

   @Autowired FraudController fraudController;
   @Autowired FooController fooController;
    // autowire all controllers

    def setup() {
        RestAssuredMockMvc.standaloneSetup(fraudController, fooController, ...) //inject all controllers
    }

}
```

That way your base class is clean. On the other hand you have a shared class and shared mock stubbing. So in one `FraudTestsConfig` you will have to stub `FraudService` for everything you need in your app. That's a drawback of this solution - but frankly speaking ATM there's no other way.

**Comment by marcingrzejszczak** [comment]
The issue has been moved to the new repo
