### ISSUE TITLE
ContractFileScanner exclude/ignore path matchers doesn't work under Windows

### ISSUE THREAD

**Issue by yu55** [Codearte/accurest#206]
`io.codearte.accurest.wiremock.RecursiveFilesConverterSpec.should recursively convert matching files with exlusions` test fails under Windows (no problem under Linux):

```
Condition not satisfied:

[Paths.get("dslRoot.json"), Paths.get("dir2/dsl2.json")] as Set == relativizedCreatedFiles as Set
       |                          |                             |  |
       dslRoot.json               dir2\dsl2.json                |  [dir1\dsl1.json, dir1\dsl1b.json, dir2\dsl2.json, dslRoot.json]
                                                                false

    at io.codearte.accurest.wiremock.RecursiveFilesConverterSpec.should recursively convert matching files with exlusions(RecursiveFilesConverterSpec.groovy:65)

```

It's because invalid pattern syntax is passed to `FileSystem.getPathMatcher()` when running under Windows.

Because of this failing test it's not possible to build Accurest under Windows.

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/Codearte/accurest/commit/cd955b1d21f5f8028b0be9a9e94bb0e12cadbfe9
