### ISSUE TITLE
Smoke testing with Maven plugin on commit/release

### ISSUE THREAD

**Issue by szpak** [Codearte/accurest#212]
Maven plugin is a little bit on the side. Maybe it would be good to perform smoke testing (simple acceptance tests) on Maven project when the main Accurest project is released (or on every commit)?

I've seen similar technique is in micro-infra-spring and boot-microservice.

**Comment by marcingrzejszczak** [comment]
In spring-cloud-contract it's all in the same repo. Everything is built and published together.
