### ISSUE TITLE
Improve support for arrays in body

### ISSUE THREAD

**Issue by mzielinski** [Codearte/accurest#217]
Assume that we have below response from server

```
{
   "exp": 2459982033,
   "user_name": "admin",
   "authorities": [
       "ROLE_ADMIN"
   ],
   "client_id": "ui",
   "scope": [
       "read",
       "write"
   ]
}
```

I would like to check wheather scope array is not empty. I do not care about specific values. Currently I am not able to do it. For sure we should improve support for arrays in body, maybe this task will be a good place to think about it.

**Comment by marcingrzejszczak** [comment]
Right now you can do it with a method on the server side.

**Comment by marcingrzejszczak** [comment]
This issue was moved to spring-cloud/spring-cloud-contract#24
