### ISSUE TITLE
Start publishing Accurest contracts together with stubs

### ISSUE THREAD

**Issue by marcingrzejszczak** [Codearte/accurest#226]
Contracts in `accurest` folder
Stubs in `mappings` folder

**Comment by mariuszs** [comment]
Stubs in `mappings` folder - standard directory for wiremock stubs.

**Comment by mariuszs** [comment]
Maybe we should change classifier to `accurest`?

**Comment by marcingrzejszczak** [comment]
https://github.com/Codearte/accurest/commit/5c2b87f6e5b1563b1ba1621238bf3b9fc05372f4
