### ISSUE TITLE
Artifacts shouldn't be installed in local Maven repo on "check" task

### ISSUE THREAD

**Issue by szpak** [Codearte/accurest#238]
Currently `gw clean check` installs snapshot artifacts in local Maven repository. It is not expected behavior for `check`.

```
$ find . -iname "*1.0.7-SNAPSHOT.jar"
./accurest-messaging-integration/1.0.7-SNAPSHOT/accurest-messaging-integration-1.0.7-SNAPSHOT.jar
./accurest-messaging-core/1.0.7-SNAPSHOT/accurest-messaging-core-1.0.7-SNAPSHOT.jar
./accurest-core/1.0.7-SNAPSHOT/accurest-core-1.0.7-SNAPSHOT.jar
```

**Comment by marcingrzejszczak** [comment]
It's deliberate cause I don't know how for Nebula tests pass to the projects those three artifacts. If you have a better idea be my guest - https://github.com/Codearte/accurest/blob/master/build.gradle#L150

**Comment by szpak** [comment]
In the previous pass I modified Nebula tests to use project build directory - jar installation shouldn't be necessary.

**Comment by dstepanov** [comment]
It's strange that there is no direct dependency from the plugin itself

**Comment by dstepanov** [comment]
This can be closed, right?
