### ISSUE TITLE
How to use stubs from classpath

### ISSUE THREAD

**Issue by pmendelski** [Codearte/accurest#256]
Hi, first of all thanks for a great peace of software.

I read the documentation on [stub runners](http://codearte.github.io/accurest/#stub-runner).
I still wonder if there is a possibility to use stubs from the classpath.

Scenario:
ServiceA depends on ServiceB.
ServiceB stubs jar is deployed on artifactory.
ServiceA has a test dependency on ServiceB stubs jar.
- Can I use stubs from the classpath?
- If yes what is the configuration for the stubrunner?

P.S. I use gradle and stub-runner-spring.

**Comment by marcingrzejszczak** [comment]
Hi!

Thanks for the kind words :)

We will be thinking about providing some full out-of-the-box solution for this. But still I guess it's possible to have it working ATM.

If you have the test dependency then most likely it gets installed in your local `.m2` isn't it? Then if you pass the `stubrunner.stubs.ids` it should be fetched from local repo.

If that's not the case (the dependency is not installed) then you would have to unzip it to some local folder from Gradle that would simulate .m2. Then you would have to provide the `stubrunner.stubs.repository.root` path to that folder.

**Comment by pmendelski** [comment]
Thanks for a prompt response.

Unfortunately gradle doesn't use maven local repo (`$HOME/.m2` directory). Instead it uses `$HOME/.gradle/caches` and it is not structured the same way. Example:

```
find .gradle | grep service-a-0.0.1-stubs.jar
.gradle/caches/modules-2/files-2.1/com.myservices/service-a/0.0.1/798d8e77e3b5715b661e9c678de17b71199bb20b/service-a-0.0.1-stubs.jar
```

I will give the unzipping solution a try.

Thanks again

**Comment by marcingrzejszczak** [comment]
Np!

**Comment by marcingrzejszczak** [comment]
I have a terrible idea ;) You could iterate over the dependencies in the gradle build and then use Aether to download the stub (the code to do that is in current master and in M3 of Stub-Runner) - https://github.com/Codearte/accurest/blob/master/stub-runner/stub-runner/src/main/groovy/io/codearte/accurest/stubrunner/AetherStubDownloader.groovy#L81 .

I think that you have a strong chance of making it work :) You'd have to add accurest-core as a classpath dependency of your buildscript and then instantiate the `AetherStubDownloader` with `StubRunnerOptions` - https://github.com/Codearte/accurest/blob/master/stub-runner/stub-runner/src/main/groovy/io/codearte/accurest/stubrunner/AetherStubDownloader.groovy#L50

**Comment by pmendelski** [comment]
I am afraid it would scare out other developers from my team ;)

**Comment by marcingrzejszczak** [comment]
:D You could hide it in a plugin ;) But actually if you could check it out manually and that would work we could try to put it into Accurest Gradle Plugin :)

**Comment by pmendelski** [comment]
I would rather go with creating a stub type dependency and use gradle to download them:

Draft solution:

```
configurations { stub }

dependencies {
    // some stub dependencies
   stub "groupId:artifactId:version"
}

task explodeStubs(type: Copy) {
    from { configurations.stubs.collect { zipTree(it) } }
    into "$build/exploded-stubs"
}
processTestResources.dependsOn explodeStubs
```

... when I find a spare moment I will dive into it. It would be really cool to be an accurest contributor :)

**Comment by marcingrzejszczak** [comment]
Wow that looks super clean actually! And we could hide all of it inside the gradle plugin !! That's awesome :D
