### ISSUE TITLE
incorrect regural expression interpretation (1.1.0-M5)

### ISSUE THREAD

**Issue by norbson** [Codearte/accurest#273]
contract body:
`
body(
                code: 9,
                message: $(client('Wrong credentials'), server(regex('^(?!\\s*$).+')))
        )
`
generates
`assertThatJson(parsedJson).field("message").matches("^(?!\\s*\$).+")`
which gives 
`error: illegal escape character
            assertThatJson(parsedJson).field("message").matches("^(?!\\s*\$).+");`

**Comment by marcingrzejszczak** [comment]
The dollar is escaped? :/

**Comment by norbson** [comment]
si :)
