### ISSUE TITLE
Response body assertion does not checks array length

### ISSUE THREAD

**Issue by gaczm** [Codearte/accurest#279]
I have endpoint that have `limit` parameter. In my contract test I would like to assert that number of elements in array is equal to expected number. Example:

Request:
`/suggest?phrase=sam&limit=3`

Response:

```
{ 
    "phrases": [ 
        { phrase: "Samsung Galaxy S5" },
        { phrase: "Samsung Galaxy S6" },
        { phrase: "Samsung Galaxy S7" }
    ]
}
```

So to check that, I wrote test:

```
io.codearte.accurest.dsl.GroovyDsl.make {
    request {
        method 'GET'
        urlPath('/suggest') {
            queryParameters {
                parameter 'phrase': 'sam'
                parameter 'limit': 3
            }
        }
        headers {
            header 'Accept': 'application/json'
            header 'Accept-Charset': 'UTF-8'
        }
    }
    response {
        status 200
        body([phrases: [
                [ phrase: "Samsung Galaxy S5"],
                [ phrase: "Samsung Galaxy S6"],
                [ phrase: "Samsung Galaxy S7"]
        ]])
    }
}
```

And assertion in generated code is:

```
DocumentContext parsedJson = JsonPath.parse(string)
assertThatJson(parsedJson).array("phrases").contains("phrase").isEqualTo("Samsung Galaxy S5")
assertThatJson(parsedJson).array("phrases").contains("phrase").isEqualTo("Samsung Galaxy S6")
assertThatJson(parsedJson).array("phrases").contains("phrase").isEqualTo("Samsung Galaxy S7")
```

And now when I change value of limit parameter, generated test still passes, cause assertion does not check array length and this may be misleading for end users.

**Comment by marcingrzejszczak** [comment]
If you need to do such an assertion I'd advise to use the `execute` block - http://codearte.github.io/accurest/#executing-custom-methods-on-server-side . Since JSON is a terrible structure it will not be that trivial to also test the size of that array.

**Comment by gaczm** [comment]
Ok, it is possible, but it makes contract unreadable... From quick look (using debugger) it would be possible to check for array size in ArrayAssertion and use that in generated specs

**Comment by marcingrzejszczak** [comment]
Yeah that could be possible - I'll try to check it out in my free time :) thanks for the hint!

**Comment by marcingrzejszczak** [comment]
JsonAssert has been adopted to verify the size of the array - https://github.com/marcingrzejszczak/jsonassert/releases/tag/jsonassert-0.4.6

**Comment by marcingrzejszczak** [comment]
@gaczm - could you please check out this branch - https://github.com/Codearte/accurest/tree/issues_%23279_array_size - build it locally and check if it's working for you? As I presumed verification of size wasn't that straight forward unfortunately...
