### ISSUE TITLE
Tests for ignored contracts should be generated with @Ignore annotation

### ISSUE THREAD

**Issue by szpak** [Codearte/accurest#28]
Now the tests are not generated at all.

**Comment by magdzikk** [comment]
I'd love to see such a feature, right now I have a case where I'd like a contract which would generate me a stub, but not a server test

**Comment by marcingrzejszczak** [comment]
@magdzikk - if we do that then you could publish to nexus a stub that hasn't been verified against the server side. What you can do however is to execute the Gradle `generateWireMockServerStub` if I'm not mistaken to get have those contracts generated without generating a test

**Comment by magdzikk** [comment]
In my case, I want to have two kinds of contracts in one project: ordinary contracts for my microservice for which I want both stubs and server tests, and some special contracts for which I only want the stubs. Those special contracts are for a 3rd party service, so I don't mind that they'll end up in nexus unverified (I'm not able to formally verify them anyway).

But indeed for now I can achieve it doing some custom gradle configuration, as @marcingrzejszczak suggested.

In case anyone ever wonders how - I have separate folders for them (`mappings/com/ofg/` for contracts of my microservice, `mappings/external-services/` for the others), and I have the value of `contractsDslDir` overriden in `generateWireMockClientStubs` to cover both folders for that task only:

```
accurest {
     contractsDslDir = file("${project.projectDir.absolutePath}/mappings/es/com/ofg/")
     //... all other standard accurest settings ...
}

generateWireMockClientStubs {
     contractsDslDir = file("${project.projectDir.absolutePath}/mappings/")
}
```

**Comment by jkubrynski** [comment]
@magdzikk @szpak you can test it with Accurest 1.0.0-RC1. It's briefly documented here: https://github.com/Codearte/accurest/wiki/8.-Migration-guide

**Comment by magdzikk** [comment]
Great, it works for my case!
