### ISSUE TITLE
Is there an example of using this with Spring Data REST?

### ISSUE THREAD

**Issue by jashatton** [Codearte/accurest#289]
I was curious if there is an example of using Accurest (Spring Cloud Contract Verifier) with Spring Data REST Repositories?  I have googled around and haven't found anything yet.  Or let me know if it is a feature that still needs to be added?

Thanks,
Jas

**Comment by marcingrzejszczak** [comment]
Hi

Actually we haven't tested that at all with Spring Data Rest so you're more
than welcome to check it out :)

**Comment by jashatton** [comment]
I actually made a start at it.  Looks like the project would need to support more than @RestController classes.  Is this becoming and "official" Spring project under Pivotal?

**Comment by marcingrzejszczak** [comment]
How are you building the project? Yes it is in progress of becoming such a project.

**Comment by jashatton** [comment]
I just ran the parent Gradle script and it errored with:

A problem occurred evaluating root project
'spring-cloud-contract-verifier-parent'.

> Could not find method findProperty() for arguments [REPO_USERNAME] on
> root project 'spring-cloud-contract-verifier-parent'.

**Comment by marcingrzejszczak** [comment]
Did you run it via `gradlew` ?

**Comment by jashatton** [comment]
I am on a Mac I ran just "gradle"

**Comment by marcingrzejszczak** [comment]
ah, run `./gradlew` - it's using Gradle 2.14 and you most likely have an old version

**Comment by jashatton** [comment]
OK that worked,  I will take a look at what it might take to add Spring Data REST support.  I believe I may have to look at RESTAssured as well.  Thanks for the help.

**Comment by marcingrzejszczak** [comment]
As @jashatton mentioned on Gitter it's enough to setup a normal `WebApplicationContext`:

```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = InvoiceApplication.class)
@ActiveProfiles("test")
@WebIntegrationTest
@Ignore // This allows wiring up of the web app context for Accurest purposes
public class BaseContractSpec {

    @Autowired
    private WebApplicationContext webApplicationContext;

    @Before
    public void setup() {
        RestAssuredMockMvc.standaloneSetup(MockMvcBuilders.webAppContextSetup(webApplicationContext));
    }
}
```
