### ISSUE TITLE
Accurest is not working under windows

### ISSUE THREAD

**Issue by marcingrzejszczak** [Codearte/accurest#30]
It's always uptodate

**Comment by jkubrynski** [comment]
Pull request would be nice - no os to check :-)

**Comment by marcingrzejszczak** [comment]
I know that it would be nice but I also don't have Windows :D

**Comment by szpak** [comment]
@marcingrzejszczak Gather logs with `--debug` and put them somewhere.

**Comment by szpak** [comment]
@marcingrzejszczak Are you sure that there were changes in GroovyDSL between consecutive `generateAccurest` calls (or anything else that could impact generated tests - like an AccuREST version modification)?

**Comment by szpak** [comment]
Btw, you can always run the task with `--rerun-tasks` as a workaround.

**Comment by szpak** [comment]
Should be fixed by PR #34.
