### ISSUE TITLE
colon inside json (e.g. hal+json links)

### ISSUE THREAD

**Issue by me3x** [Codearte/accurest#32]
I tried to use hal+json and there is an error in generated Spec. Links should be in quotes, becasue it contains colon. It shoul look like this: responseBody._links == [self:[href:'http://localhost:8095/clients/1']]. The output looks like this and is not valid: responseBody._links == [self:[href:http://localhost:8095/clients/1]]

{
  "firstName" : "Test",
  "lastName" : "Test",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8095/clients/1"
    }
  }
}

**Comment by jkubrynski** [comment]
Could you paste full dsl you are using?

**Comment by me3x** [comment]
```
io.coderate.accurest.dsl.GroovyDsl.make {
    request {

        method 'GET'
        url $(client(regex('/clients/[0-9]{2}')), server('/clients/1'))

        headers {
            header 'Content-Type': 'application/hal+json'
        }

    }
    response {
        status 200
        headers {
            header 'Content-Type': 'application/hal+json'
        }
        body '''\
{
  "firstName" : "Test",
  "lastName" : "Test",
  "age" : 25,
  "loanId" : "testId",
  "_links" : {
    "self" : {
      "href" : "'http://localhost:8095/clients/1'"
    }
  }
}
'''
    }
}
```

**Comment by jkubrynski** [comment]
I've released version 0.4.2 with fix for map elements assertions. Regarding colon there is no error, you just have to use `"href" : "http://localhost:8095/clients/1"` (without single quote) in your DSL.

**Comment by me3x** [comment]
There is an error - single quotes are workaround. It takes http: part as the other expression without it.

/var/lib/jenkins/jobs/client-service-cz/workspace/src/test/groovy/accurest/ClientsSpec.groovy: 39: illegal colon after argument expression;
   solution: a complex label expression before a colon must be parenthesized @ line 39, column 43.
   ody._links == [self:[href:http://localho
                                 ^

**Comment by me3x** [comment]
```
/var/lib/jenkins/jobs/client-service-cz/workspace/src/test/groovy/accurest/ClientsSpec.groovy: 39: illegal colon after argument expression;
   solution: a complex label expression before a colon must be parenthesized @ line 39, column 43.
   ody._links == [self:[href:http://localho
                                 ^
```

**Comment by jkubrynski** [comment]
@me3x if you use standard string notation "http://localhost:8082" it works without errors

**Comment by me3x** [comment]
Nope, because quotes are removed.

**Comment by me3x** [comment]
Here is a DSL without workaround, that produced the error:

```
io.coderate.accurest.dsl.GroovyDsl.make {
    request {

        method 'GET'
        url $(client(regex('/clients/[0-9]{2}')), server('/clients/1'))

        headers {
            header 'Content-Type': 'application/hal+json'
        }

    }
    response {
        status 200
        headers {
            header 'Content-Type': 'application/hal+json'
        }
        body '''\
{
  "firstName" : "Test",
  "lastName" : "Test",
  "age" : 25,
  "loanId" : "testId",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8095/clients/1"
    }
  }
}
'''
    }
}
```

**Comment by me3x** [comment]
The one I sent you before is working with workaround implemented already. Sorry I sent it by mistake.

**Comment by jkubrynski** [comment]
@me3x using normal strings is not a walkaround - it's just proper DSL generating proper groovy code

**Comment by me3x** [comment]
You still don't get it... 

```
This is not working: "http://localhost:8095/clients/1"
This is working: "'http://localhost:8095/clients/1'"
```

The second one is woking and it is workaround because of the additional quotes.
The first one is not and here is the resulted error - qotes are missing in the generated Spec even thought they are in the DSL. 

```
/var/lib/jenkins/jobs/client-service-cz/workspace/src/test/groovy/accurest/ClientsSpec.groovy: 39: illegal colon after argument expression;
   solution: a complex label expression before a colon must be parenthesized @ line 39, column 43.
   ody._links == [self:[href:http://localho
                                 ^
```

**Comment by jkubrynski** [comment]
For this DSL

```
"_links" : {
    "self" : {
      "href" : "http://localhost:8095/clients/1"
    }
  }
```

accurest generates such Groovy code:

```
responseBody._links.self.href == "http://localhost:8095/clients/1"
```

**Comment by me3x** [comment]
I tried it now with version 0.4.1 and result is this:

```
responseBody._links == [self:[href:http://localhost:8095/clients/1]]
```

**Comment by jkubrynski** [comment]
Try with 0.4.2 and let me know

**Comment by me3x** [comment]
works with 0.4.2 :+1: so you fixed it :)

**Comment by jkubrynski** [comment]
Great :)
