### ISSUE TITLE
Default test task in project should depend on generateAccurest

### ISSUE THREAD

**Issue by szpak** [Codearte/accurest#36]
To run also generated tests. Currently it has to be done in `build.gradle` of the end project.

**Comment by marcingrzejszczak** [comment]
That's pretty important to do. Any volunteers? :)

**Comment by jkubrynski** [comment]
The question is if we want to have this by default? For some people having it in separate task could be a profit

**Comment by marcingrzejszczak** [comment]
Spencer tried to run it while running `./gradlew build` and was surprised
to see that it's not working.

Maybe by default it should work likes this but could have a flag that could
be overridden by a system / project prop?

**Comment by OlgaMaciaszek** [comment]
Right now `generateAccurest` is being triggered before compileTestGroovy`:

``` groovy
project.compileTestGroovy.dependsOn(GENERATE_SERVER_TESTS_TASK_NAME)
```

What is not being done by default at any point in the standard build flow is `generateWiremockClientStubs`.

What standard build tasks should Accurest tasks  be linked to?

**Comment by marcingrzejszczak** [comment]
Let's do it like this maybe. We could in the `accurest` section in Gradle plugin configuration provide the strategy type (by default WireMock) and basing on that append the proper `generate...ClientStubs` task?

**Comment by marcingrzejszczak** [comment]
accurest depends on check so it's solved
