### ISSUE TITLE
Handling of optional parameters from request body when generating wiremock stubs

### ISSUE THREAD

**Issue by cbuleandra** [Codearte/accurest#42]
It is not currently possible to use the Groovy DSL for creating stub definitions with request bodies that  accept optional parameters. It would be nice if something like this could be defined using the Groovy DSL:

```
${$(client(~/('loanNumber': '[0-9]+')?/), server('"loanNumber": 321'))}
```

This should then result in the following stub definition:

```
"bodyPatterns": [
    { "matches": "\\{(\"loanNumber\":\"[0-9]+\")?\\}" }
]
```

I guess nothing should have to change on the acceptance tests generation part.

What do you think? If you're ok with this idea, I could start working on a pull request in the following days.

**Comment by marcingrzejszczak** [comment]
Definite +1

**Comment by marcingrzejszczak** [comment]
@cbuleandra you can check https://github.com/Codearte/accurest/pull/154/files to see how it will look like

**Comment by marcingrzejszczak** [comment]
Done with https://github.com/Codearte/accurest/commit/4126eafd4cb777b3789f548009d7de7107afc190

**Comment by cbuleandra** [comment]
@marcingrzejszczak Look great, thanks! Great job, as always! :+1:

**Comment by mariuszs** [comment]
This is not implemented

**Comment by norbson** [comment]
Implementation does not meet presented use case.
The idea was to define optional body elements. Your implementation allow to define optional value of such element but does not allow for optional element

Example:
`description: $(stub(optional(regex('.+'))), test('Short term loans'))` generates
`"matchesJsonPath" : "$[?(@.description =~ /(.+)?/)]"`

**Comment by marcingrzejszczak** [comment]
So if the field is optional why do you need to put it into the DSL?

**Comment by norbson** [comment]
Maybe because of this is a part of a public contract and such information should be explicit. Also I want this part on test side.

**Comment by marcingrzejszczak** [comment]
This issue was moved to spring-cloud/spring-cloud-contract#22
