### ISSUE TITLE
Support Callable closure in response

### ISSUE THREAD

**Issue by me3x** [Codearte/accurest#47]
Response body is empty with Callable closure as response in controller. You'll have to wait for response because it's async.

**Comment by jkubrynski** [comment]
The problem with async calls is that they are not supported in RestAssured library we're using. We'll see how we can address this issue

**Comment by marcingrzejszczak** [comment]
PR waiting for review - https://github.com/jayway/rest-assured/pull/39

**Comment by marcingrzejszczak** [comment]
since rest assured 2.5.0 the feature is available - https://github.com/jayway/rest-assured/wiki/Usage#asynchronous-requests

**Comment by mattreyuk** [comment]
I need this too for my controllers returning a `DeferredResult`. I manually updated one of the generated tests to add `when().async()` and the test now passes. The problem is, that will fail for a regular synchronous call with an `Async started expected` assertion fail. I'd like to have a go at providing a PR for this but it will need an addition to the DSL to flag if the call is async. What do you think about an optional `async:true` flag in the `response` structure?

**Comment by marcingrzejszczak** [comment]
Yeah I didn't have time to do that, sorry... :/

how about:

```

io.codearte.accurest.dsl.GroovyDsl.make {
    request {
        //...
    }
    response 
        //...
        async()
    }
}

```

WDYT?

**Comment by mattreyuk** [comment]
ok by me. Now I know nothing about Groovy but I figure I need to change the `getInputString()` methods in the builder `JunitMethodBodyBuilder.groovy` and `SpockMethodRequestProcessingBodyBuilder.groovy`classes on the basis of that `async` flag. I'm just not sure how to define `async()` in the DSL. I see I can access the `response` object in those classes so I'm assuming once it's there, I'll be able to check for it...

**Comment by marcingrzejszczak** [comment]
so... let's start from the last part

we could do (if that has to be in Response - cause maybe it should be in Request? - dunno).

```
class Response extends Common {

    DslProperty status
    DslProperty delay
    Headers headers
    Body body
        boolean async


        public void async() {
             this.async = true
         }
...

```

now, basing on that Spock and JUnit changes as you've mentioned.  You can check the `MethodBodyBuilder` to see all the blocks. I think we need to change the `whenBlock` right? And we're back at what you said :D Yes you have to change the `getInputString()`.

So for Spock it is sth like that

```
@Override
    protected String getInputString(Request request) {
        return 'def response = given().spec(request)'
    }
```

and it would be (pseudocode)

```
@Override
    protected String getInputString(Request request) {
                if(request.async) {
                    return 'def response = given().async().spec(request)' 
                }
        return 'def response = given().spec(request)'
    }
```

Sth like that ?

Can you write what you wrote for the test to pass? I don't remember what I did in Rest Assured to tell you the truth :D

**Comment by mattreyuk** [comment]
I think it makes sense to have it in the response - it's the response that's returned async. That gives me plenty to get going thanks!
