### ISSUE TITLE
There is no mapping from 'bodyPattern' (WireMock definition) to 'body' (Groovy DSL) in WiremockToDslConverterc class

### ISSUE THREAD

**Issue by mzielinski** [Codearte/accurest#49]
Version: 0.4.5

Object com.oberthur.contract.validation.wiremock.WiremockToDslConverter should map bodyPatterns to body.

As a result generated GroovyDsl do not contains body in request part.

**Comment by marcingrzejszczak** [comment]
should be fixed by https://github.com/Codearte/accurest/pull/54 - could you please build a SNAPSHOT version from current MAIN and check if it's working as it should?

**Comment by mzielinski** [comment]
Fix didn't resolved this issue. Problem is in class com.oberthur.contract.validation.wiremock.WiremockToDslConverter which was not changed.

There should be also converting for regex, which was add in 0.6.0 version

**Comment by marcingrzejszczak** [comment]
Can you provide an example of such a wiremock JSON stub?

**Comment by mzielinski** [comment]
Yes, of course :)

``` groovy
{
  "request" : {
    "url" : "/test",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalToJson" : "{\"property1\":\"abc",\"property2\":\"2017-01\",\"property3\":\"666\",\"property4\":1428566412}"
    } ],
    "headers" : {
      "Content-Type" : {
        "equalTo" : "application/json"
      }
    }
  },
  "response" : {
    "status" : 200,
    "body" : "{\"status\":\"OK\",\"csc\":\"\\d{3}\"}",
    "headers" : {
      "Content-Type" : "application/json"
    }
  }
}
```

**Comment by marcingrzejszczak** [comment]
Could you please check out - https://github.com/Codearte/accurest/pull/60 ? Maybe you can build a snapshot version and verify if suits your needs.

**Comment by mzielinski** [comment]
It is fixed. Thanks
