### ISSUE TITLE
Simplify exclude/ignore files with FileNameFinder?

### ISSUE THREAD

**Issue by szpak** [Codearte/accurest#53]
I accidentally found [FileNameFinder](http://docs.groovy-lang.org/latest/html/gapi/groovy/util/FileNameFinder.html). Could it be used?
http://mrhaki.blogspot.com/2009/11/groovy-goodness-finding-files-with.html

Or AccuREST needs something more?

**Comment by jkubrynski** [comment]
It looks it's useful but it requires bigger refactoring of TestGenerator class

**Comment by jkubrynski** [comment]
We've moved to PathPattern
