### ISSUE TITLE
Plugin should add a task 'publishStubs'

### ISSUE THREAD

**Issue by marcingrzejszczak** [Codearte/accurest#6]
it could add by default a classifier 'stub' (that could be configurable) - take a look at https://github.com/4finance/micro-infra-spring/issues/213

**Comment by marcingrzejszczak** [comment]
@szpak - aren't you doing this with @cameeleck right now?

**Comment by szpak** [comment]
Stub packaging (and publishing) is not a part of accurest and has to be configured in end application. There is an example in [boot-microservice](https://github.com/4finance/boot-microservice/blob/5c4e227132f356a86b97054062e316ec32bc0709/build.gradle#L193-L231).

On `publish` both fat jar and a jar with stubs are published. Stubs alone can be publish with `publishStubsPublicationToMavenLocal` or `publishStubsPublicationToMavenRepository`.

**Comment by marcingrzejszczak** [comment]
Agreed. We will have to create an in-house plugin with stuff like that
