### ISSUE TITLE
Task for validating contract dsl's

### ISSUE THREAD

**Issue by jkubrynski** [Codearte/accurest#7]
Because we can have separate fields for customer and server we should provide possibility to verify if there are no mistakes (running customer regex over server field). For example

```
url {
  customer matches "\/users\/[0-9]+$"
  server equalTo "/users/123"
}
```

will be validated positively while

```
url {
  customer matches "\/users\/[0-9]+$"
  server equalTo "/users/123a"
}
```

will fail

**Comment by marcingrzejszczak** [comment]
Maybe this can be useful:

http://groovy.codehaus.org/Type+checking+extensions
http://groovy.codehaus.org/Advanced+compiler+configuration

**Comment by marcingrzejszczak** [comment]
Done in - https://github.com/Codearte/accurest/pull/63
