### ISSUE TITLE
Add plugability of groovy dsl via SPI

### ISSUE THREAD

**Issue by marcingrzejszczak** [Codearte/accurest#8]
Let's add possibility for people to add transformations to other things than Wiremock stubs or test code. There are other Http stub servers like Moco Mountback (don't remember if spelled it correctly) etc.

**Comment by szpak** [comment]
Probably [gipsy](https://github.com/aalmiray/gipsy) could be useful to integrate with SPI mechanism in Java.

**Comment by marcingrzejszczak** [comment]
This issue was moved to spring-cloud/spring-cloud-contract#23
