### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by spencergibb** [Codearte/accurest#96]
Any technical limitations that might prevent a maven plugin?  I might take a shot at PR if there is not.

**Comment by marcingrzejszczak** [comment]
No technical limitations.

In Gradle with the plugin we are ensuring:
- generation of Spock tests from Groovy DSL
- creation of Wiremock stubs from the same Groovy DSL

and that's pretty much it - @jkubrynski ?

**Comment by jkubrynski** [comment]
Exactly. In fact gradle plugin is just launching proper methods from accurest-core module providing project configuration and paths.

**Comment by mariuszs** [comment]
https://github.com/Codearte/accurest-maven-plugin
